<?php

namespace App\Http\Controllers\Okapi;

use App\Http\Controllers\Controller;
use App\Models\Okapi\Type;

class DocumentationController extends Controller
{

    public function __invoke()
    {
        $documentation = [
            [
                'swagger' => '2.0',
                'info' => [
                    'description' => 'This is a Swagger documentation generated by okAPI.
                You can find more about Swagger at [https://swagger.io](https://swagger.io)
                You can find more about okAPI on [GitHub](https://github.com/smitoi/okapi).'
                ],
                'version' => '1.0.0',
                'title' => config('app.name'),
            ],
            'host' => config('app.url'),
            'basePath' => '/api',
            'tags' => [],
            'paths' => [],
        ];

        /** @var Type $type */
        foreach (Type::query()->get() as $type) {
            $documentation['tags'][] = [
                'name' => $type->name,
            ];
        }
    }
}
